graph:
  directed: False
  #edge_info: [[0, 1, 1], [1, 2, 1], [2, 3, 1], [3, 0, 1]]
  edge_info: [[0, 1, 1], [1, 2, 1], [2, 0, 1]]
  is_eig: True
  numNodes: 3
connectionGraph:
  connectionDim: 3  # Options [2,3]
  #edgeRotations: [[90, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
  edgeRotations: [[90, 0, 0], [0, 0, 0], [0, 0, 0]]
optimizer:
  g_type: 'g_opt'  # Options are ['g_opt', 'g_init']
