graph:
  directed: False
  edge_info: [[0, 1, 1], [1, 2, 1], [2, 3, 1], [3, 0, 1], [3, 4, 1], [4, 5, 1], [5, 0, 1]]
  is_eig: True
  numNodes: 6
connectionGraph:
  connectionDim: 3
  edgeRotations: [[0.1, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
optimizer:
  g_type: 'g_opt'  # Options are ['g_opt', 'g_init', 'g_evec']
